services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - venv:/app/.venv
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PSEUDONYMIZATION_SALT: ${PSEUDONYMIZATION_SALT}
      PYTHONPATH: /app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - brif_network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./includes/sql/staging.sql:/docker-entrypoint-initdb.d/staging.sql:ro
      - ./includes/sql/core.sql:/docker-entrypoint-initdb.d/core.sql:ro
      - ./includes/sql/airflow.sql:/docker-entrypoint-initdb.d/airflow.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - brif_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - brif_network

  airflow:
    image: apache/airflow:3.3.1
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres:5432/${AIRFLOW_DB}
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/dags
      PYTHONPATH: /opt/airflow/project
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - .:/opt/airflow/project
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - brif_network
    command: airflow standalone # Cette command pour installer touts les composent de airflow automatique

volumes:
  postgres_data:
  venv:

networks:
  brif_network: